---
apiVersion: v1
kind: ConfigMap
metadata:
  name: taskapp-config
  namespace: taskapp
data:
  POSTGRES_DB: taskapp
  POSTGRES_USER: taskapp
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  DATABASE_NAME: taskapp
  DATABASE_USER: taskapp
  FLASK_ENV: production