[k3s_server]
server ansible_host=51.20.133.199 private_ip=10.0.1.39

[k3s_agents]
worker0 ansible_host=16.170.98.99 private_ip=10.0.1.198
worker1 ansible_host=13.49.76.89 private_ip=10.0.1.66

[k3s_cluster:children]
k3s_server
k3s_agents